import {
  EXPO_PUBLIC_COMETCHAT_APP_ID,
  EXPO_PUBLIC_COMETCHAT_AUTH_KEY,
  EXPO_PUBLIC_COMETCHAT_REGION,
} from '@/config/env';

export const COMETCHAT_APP_ID = EXPO_PUBLIC_COMETCHAT_APP_ID;
export const COMETCHAT_REGION = EXPO_PUBLIC_COMETCHAT_REGION;
export const COMETCHAT_AUTH_KEY = EXPO_PUBLIC_COMETCHAT_AUTH_KEY;
